Fix clippy lints updates from 1.97
The question_mark lint now lints more cases when if let is used

```
error: this block may be rewritten with the `?` operator
   --> src/index_map.rs:190:13
    |
190 | /             if let Some(pos) = self.indices[probe] {
191 | |                 let entry_hash = pos.hash();
192 | |                 // NOTE(i) we use unchecked indexing below
193 | |                 let i = pos.index();
...   |
205 | |                 return None;
206 | |             }
    | |_____________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.97.0/index.html#question_mark
    = note: `-D clippy::question-mark` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::question_mark)]`
help: replace it with
    |
190 ~             {
191 +                 let pos = self.indices[probe]?;
192 +                 let entry_hash = pos.hash();
193 +                 // NOTE(i) we use unchecked indexing below
194 +                 let i = pos.index();
195 +                 debug_assert!(i < self.entries.len());
196 +
197 +                 if dist > entry_hash.probe_distance(Self::mask(), probe) {
198 +                     // give up when probe distance is too long
199 +                     return None;
200 +                 } else if entry_hash == hash
201 +                     && unsafe { self.entries.get_unchecked(i).key.borrow() == query }
202 +                 {
203 +                     return Some((probe, i));
204 +                 }
205 +             }
    |
```

```
error: this block may be rewritten with the `?` operator
   --> src/pool/treiber/cas.rs:230:9
    |
230 | /         if let Some(mut top) = stack.top.load(Ordering::Acquire) {
231 | |             let next = unsafe { top.non_null().as_ref().next().load(Ordering::Relaxed) };
232 | |
233 | |             if stack
...   |
280 | |             return None;
281 | |         }
    | |_________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.97.0/index.html#question_mark
help: replace it with
    |
230 ~         {
231 +             let mut top = stack.top.load(Ordering::Acquire)?;
232 +             let next = unsafe { top.non_null().as_ref().next().load(Ordering::Relaxed) };
233 +
234 +             if stack
235 +                 .top
236 +                 .compare_and_exchange_weak(Some(top), next, Ordering::Release, Ordering::Relaxed)
237 +                 .is_ok()
238 +             {
239 +                 // Prevent the ABA problem (https://en.wikipedia.org/wiki/Treiber_stack#Correctness).
240 +                 //
241 +                 // Without this, the following would be possible:
242 +                 //
243 +                 // | Thread 1                      | Thread 2                | Stack                        |
244 +                 // |-------------------------------|-------------------------|------------------------------|
245 +                 // | push((1, 1))                  |                         | (1, 1)                       |
246 +                 // | push((1, 2))                  |                         | (1, 2) -> (1, 1)             |
247 +                 // | p = try_pop()::load // (1, 2) |                         | (1, 2) -> (1, 1)             |
248 +                 // |                               | p = try_pop() // (1, 2) | (1, 1)                       |
249 +                 // |                               | push((1, 3))            | (1, 3) -> (1, 1)             |
250 +                 // |                               | push(p)                 | (1, 2) -> (1, 3) -> (1, 1)   |
251 +                 // | try_pop()::cas(p, p.next)     |                         | (1, 1)                       |
252 +                 //
253 +                 // As can be seen, the `cas` operation succeeds, wrongly removing pointer `3` from
254 +                 // the stack.
255 +                 //
256 +                 // By incrementing the tag before returning the pointer, it cannot be pushed again
257 +                 // with the, same tag, preventing the `try_pop()::cas(p, p.next)`
258 +                 // operation from succeeding.
259 +                 //
260 +                 // With this fix, `try_pop()` in thread 2 returns `(2, 2)` and the comparison
261 +                 // between `(1, 2)` and `(2, 2)` fails, restarting the loop and
262 +                 // correctly removing the new top:
263 +                 //
264 +                 // | Thread 1                      | Thread 2                | Stack                        |
265 +                 // |-------------------------------|-------------------------|------------------------------|
266 +                 // | push((1, 1))                  |                         | (1, 1)                       |
267 +                 // | push((1, 2))                  |                         | (1, 2) -> (1, 1)             |
268 +                 // | p = try_pop()::load // (1, 2) |                         | (1, 2) -> (1, 1)             |
269 +                 // |                               | p = try_pop() // (2, 2) | (1, 1)                       |
270 +                 // |                               | push((1, 3))            | (1, 3) -> (1, 1)             |
271 +                 // |                               | push(p)                 | (2, 2) -> (1, 3) -> (1, 1)   |
272 +                 // | try_pop()::cas(p, p.next)     |                         | (2, 2) -> (1, 3) -> (1, 1)   |
273 +                 // | p = try_pop()::load // (2, 2) |                         | (2, 2) -> (1, 3) -> (1, 1)   |
274 +                 // | try_pop()::cas(p, p.next)     |                         | (1, 3) -> (1, 1)             |
275 +                 top.increment_tag();
276 +
277 +                 return Some(top);
278 +             }
279 +         }
```